#!/usr/bin/env python
# The line above is important so that this file is interpreted with Python when running it.
# robot_leader, written by Elliot Potter
# Oct 2022, with other code used from last fall

# Import of python modules.
import math  # use of pi.
import tf  # library for transformations
import rospy  # module for ROS APIs
from std_msgs.msg import String
import json
import numpy
from leader_follower.msg import FollowerReq
from leader_follower.srv import RequestFollowers, RequestFollowersResponse
from leader_follower.msg._DriveToTargetAction import DriveToTargetAction
from leader_follower.simple_motion import SimpleMotion
import actionlib

REGISTERY_NAME = "/register_followers"


class RobotLeader:
    def __init__(self, bot_id):
        self.bot_name = "robot_" + str(bot_id)
        self.waypoint_callback = rospy.Subscriber("/waypoints", String, self.waypoint_callback)
        self.follower_requester = rospy.Publisher("/subscribe_request", FollowerReq, queue_size=1)
        # Setting up transformation listener.
        self.listener = tf.TransformListener()

        # the array of points that the followers could go to
        self.waypoint_array = []
        # the array of follower points
        self.follower_array = []
        self.server = rospy.Service(REGISTERY_NAME, RequestFollowers, self.handle_request_followers)

        self.ready_for_next_drive = True
        self.is_driving = False

    def waypoint_callback(self, msg):
        """Stores the waypoints"""
        json_string = msg.data
        self.waypoint_array = json.loads(json_string)

    def send_request_to_followers(self):
        """send request to robot followers for them to sign up"""
        print("Sending follower request")
        req = FollowerReq()
        req.service_name = REGISTERY_NAME
        self.follower_requester.publish(req)

    def handle_request_followers(self, req):
        """Adds follower to the follower array"""
        name = req.robot_name
        print("Received follower service message from robot " + name)
        if name not in self.follower_array:
            self.follower_array.append(name)
        # return success message
        return RequestFollowersResponse(1)

    def allocate_goals_robots(self):
        """
        Waits until goals have been received, and number of goals equals number of robots
        Then greedily assigns robots to goals
        """

        # wait until we have waypoints and enough robots to cover them
        while (len(self.waypoint_array) == 0 or
               len(self.follower_array)+1 != len(self.waypoint_array) or not
               self.ready_for_next_drive
        ):
            print(len(self.waypoint_array))
            print(len(self.follower_array)+1)
            print(self.ready_for_next_drive)
            rospy.sleep(1)

        print("Allocating Goals to Robots")
        # loop over waypoints, pairing them with the closest robot
        used_robots = []
        waypoint_robot_pairs = []
        for point in self.waypoint_array:
            min_distance = numpy.inf
            min_distance_bot = ""
            min_distance_point = (0, 0)
            for bot in self.follower_array + [self.bot_name]:
                if bot in used_robots:
                    continue

                # convert the point into bot coords
                (trans, rot) = self.listener.lookupTransform('world', bot + '/base_link', rospy.Time(0))
                t = tf.transformations.translation_matrix(trans)
                R = tf.transformations.quaternion_matrix(rot)

                world_T_baselink = t.dot(R)
                target_np = world_T_baselink.dot(
                    numpy.array([point[0], point[1], 0, 1])
                )

                # convert 0,0 into bot coords
                robot_np = world_T_baselink.dot(
                    numpy.array([point[0], point[1], 0, 1])
                )

                # calculate distance between the two
                distance = math.sqrt(math.pow(target_np[0]-robot_np[0], 2) + math.pow(target_np[1]-robot_np[1], 2))

                # evaluate if this bot is closer than previous closest
                if distance < min_distance:
                    min_distance = distance
                    min_distance_bot = bot
                    min_distance_point = (target_np[0], target_np[1])

            waypoint_robot_pairs.append((min_distance_bot, min_distance_point))
            used_robots.append(min_distance_bot)

        print("Pairs: " + str(waypoint_robot_pairs))
        self.ready_for_next_drive = False
        client_list = []
        leader_coords = (0, 0)
        for pair in waypoint_robot_pairs:
            if pair[0] == self.bot_name:
                leader_coords = pair[1]
                continue

            server_loc = "/drive_" + pair[0]
            print("Looking for action server at " + server_loc)
            client = actionlib.SimpleActionClient(server_loc, DriveToTargetAction)
            client.wait_for_server()
            print("Found action server at " + server_loc)
            # set x,y for the goal
            goal = DriveToTargetAction(pair[1][0], pair[1][1])
            client.send_goal(goal)
            client_list.append(client)

        # trigger the leader to drive to the point
        self.drive_leader(leader_coords[0], leader_coords[1])

        # wait for all callbacks
        for client in client_list:
            client.wait_for_result()
        self.ready_for_next_drive = True

    def drive_leader(self, x, y):
        """Drives the robot to the target"""
        if self.is_driving:
            return
        self.is_driving = True
        simple_motion = SimpleMotion()
        current_point = (0, 0)
        current_orientation = 0
        desired_point = (x, y)
        simple_motion.rotate_to_point(current_orientation, current_point, desired_point)
        simple_motion.drive_to_point(current_point, desired_point)
        self.is_driving = False


if __name__ == "__main__":
    rospy.init_node('robot_leader')
    robot_index = rospy.get_param("robot_index")
    leader = RobotLeader(robot_index)
    rospy.sleep(2)
    leader.send_request_to_followers()
    leader.allocate_goals_robots()

