#!/usr/bin/env python
# The line above is important so that this file is interpreted with Python when running it.
# robot_leader, written by Elliot Potter
# Oct 2022, with other code used from last fall

# Import of python modules.
import math  # use of pi.
import tf  # library for transformations
import rospy  # module for ROS APIs
from std_msgs.msg import String
import json


class RobotFollower:
    def __init__(self):

# TODO -- subscriber for custom msg

# TODO -- ROS service client

# TODO -- ROS action server

# TODO -- waits for another action initiation


if __name__ == "__main__":
    rospy.init_node('robot_follower')
