#!/usr/bin/env python
# The line above is important so that this file is interpreted with Python when running it.
# waypoint_broadcaster, written by Elliot Potter
# Oct 2022, with other code used from last fall

# Import of python modules.
import math  # use of pi.
import tf  # library for transformations.

# Import of python modules.
import math  # use of pi.
import tf  # library for transformations.
import json

# import of relevant libraries.
import rospy  # module for ROS APIs
from std_msgs.msg import String

FREQUENCY = 10  # freq for publishing transforms


if __name__ == '__main__':
    rospy.init_node('waypoint_node')
    orientation = rospy.get_param("num_robots")

    pub = rospy.Publisher("/waypoints", String, queue_size=1)
    msg = String()

    msg.data = json.dumps([(1, 1), (0, 3), (-2, -3)])

    rate = rospy.Rate(FREQUENCY)
    while not rospy.is_shutdown():
        pub.publish(msg)
        rate.sleep()

